name: docs
description: 문서 업데이트가 있나요?
title: "[docs] "
labels: ["docs"]
body:
  - type: textarea
    id: docs-update
    attributes:
      label: 📄 문서 업데이트 상세 내용
      description: 문서 업데이트에 대한 주요 정보를 아래 가이드라인에 따라 작성해 주세요.
      placeholder: |
        다음 정보를 포함하여 문서 업데이트 내용을 작성해 주세요:

        - 문서 업데이트에 대해 자세히 설명해 주세요.
        - 어떤 문서가 업데이트되어야 하는지, 왜 업데이트가 필요한지 명확히 기술해 주세요.

        위의 항목들을 모두 포함하여 상세하게 작성할수록 문서 업데이트 작업에 도움이 됩니다.
    validations:
      required: true
