name: refactor
description: 코드 리팩터링이 있습니까? 이는 동작을 변경하지 않습니다.
title: "[refactor] "
labels: ["refactor"]
body:
  - type: markdown
    attributes:
      value: |
        > 파울러의 조언: 리팩터링은 외부 동작을 변경하지 않고 내부 구조를 개선하는 것입니다. 
        > 새로운 기능 추가는 리팩터링이 아닙니다. 두 작업을 명확히 구분하여 진행하세요.

        예시:
        1. 리팩토링:
           - 긴 함수를 여러 개의 작은 함수로 나누기
           - 복잡한 if-else 문을 전략 패턴으로 변경하기
           - 하드코딩된 문자열을 상수로 추출하기

        2. 기능 추가 (리팩토링이 아님):
           - 새로운 사용자 인증 방식 추가하기
           - 데이터베이스에 새 필드 추가하고 관련 로직 구현하기
           - 새로운 API 엔드포인트 만들기

        3. 버그 고치기
           - **버그를 고치는 것은 리팩토링이 아닙니다!**
           - refactor태그가 아닌 feat테그를 넣고 작성해주세요.

  - type: textarea
    id: refactor-description
    attributes:
      label: 📄 설명
      description: 리팩터링 변경 사항을 설명해주세요.
      placeholder: 자세한 설명을 제공해주세요!
    validations:
      required: true
