name: setting
description: ν”„λ΅μ νΈ κµ¬μ„± λ³€κ²½μ„ ν•κ³  μμµλ‹κΉ?
title: "[setting] "
labels: ["setting"]
body:
  - type: textarea
    id: setting-details
    attributes:
      label: π“„ κµ¬μ„± λ³€κ²½ μƒμ„Έ λ‚΄μ©
      description: ν”„λ΅μ νΈ κµ¬μ„± λ³€κ²½μ— λ€ν•΄ μ„¤λ…ν•΄μ£Όμ„Έμ”.
      placeholder: |
        λ‹¤μ λ‚΄μ©μ„ ν¬ν•¨ν•μ—¬ μ‘μ„±ν•΄μ£Όμ„Έμ”:

        - μ–΄λ–¤ κµ¬μ„±μ„ λ³€κ²½ν•λ‚μ”? 
        - μ: 
            - npm μΆ…μ†μ„± μ¶”κ°€
            - package-lock.json λ³€κ²½
            - .env ν™κ²½ λ³€μ κ΄€λ ¨ μ„Έν… λ³€κ²½
            - κ·Έμ™Έ(λ””λΉ„ μ„Έν…, λ°°ν¬ ν™κ²½ κ΄€λ ¨ μ„Έν… λ³€κ²½)

        μ£Όμμ‚¬ν•­:
        - npm μΆ…μ†μ„± μ¶”κ°€ μ‹ μ •ν™•ν• λ²„μ „μ„ λ…μ‹ν•΄μ£Όμ„Έμ”.
        - package-lock.json λ³€κ²½ μ‹ μ „μ²΄ ν€μ— κ³µμ ν•΄μ£Όμ„Έμ”.
        - ν™κ²½ λ³€μ λ³€κ²½ μ‹ .env.example νμΌλ„ μ—…λ°μ΄νΈν•΄μ£Όμ„Έμ”.
    validations:
      required: true

  - type: textarea
    id: setting-notes
    attributes:
      label: π“ μ¶”κ°€ λ©”λ¨
      description: κΈ°νƒ€ κ³ λ ¤μ‚¬ν•­μ΄λ‚ μ£Όμμ μ΄ μλ‹¤λ©΄ μ‘μ„±ν•΄μ£Όμ„Έμ”.
    validations:
      required: false
