name: 테스트
description: 테스트(E2E테스트, 통합테스트, 테스트 관련 세팅)
title: '[test] '
labels: ['test']
body:
  - type: textarea
    id: test-details
    attributes:
      label: 📄 테스트 상세 내용
      description: 추가하거나 수정하는 테스트에 대해 설명해주세요.
      placeholder: |
        시간이 없다면 `테스트 대상`과 `테스트 유형`만이라도 적어주세요
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **⚠️시간이 없다면 `테스트 대상`과 `테스트 유형`만이라도 적어주세요⚠️**

        ### 1. 테스트 대상:
        - 어떤 기능 또는 컴포넌트를 테스트하나요?

        ### 2. 테스트 유형:
        - 단위 테스트, 통합 테스트, E2E 테스트 중 어떤 유형인가요?

        ### 3. 테스트 시나리오:
        - 어떤 상황을 테스트하나요? (정상 케이스, 경계값, 예외 상황 등)

        ### 주의사항:
        - 테스트는 독립적이고 반복 가능해야 합니다.
        - 모든 중요한 로직에 대해 테스트를 작성해주세요.
        - 테스트 실행 시간을 고려하세요. 너무 긴 테스트는 CI/CD 파이프라인에 부담을 줄 수 있습니다.
