name: test
description: 테스트를 추가하거나 수정하고 있습니까?
title: "[test] "
labels: ["test"]
body:
  - type: textarea
    id: test-details
    attributes:
      label: 📄 테스트 상세 내용
      description: 추가하거나 수정하는 테스트에 대해 설명해주세요.
      placeholder: |
        다음 내용을 포함하여 작성해주세요.(권장사항)
        **시간이 없다면 테스트 대상과 테스트 유형만이라도 적어주세요**

        1. 테스트 대상:
        - 어떤 기능 또는 컴포넌트를 테스트하나요?

        2. 테스트 유형:
        - 단위 테스트, 통합 테스트, E2E 테스트 중 어떤 유형인가요?

        3. 테스트 시나리오:
        - 어떤 상황을 테스트하나요? (정상 케이스, 경계값, 예외 상황 등)

        4. 작업 목록:
        - [ ] 테스트 케이스 작성
        - [ ] 테스트 실행 및 결과 확인
        - [ ] 테스트 커버리지 확인 (필요시)

        주의사항:
        - 테스트는 독립적이고 반복 가능해야 합니다.
        - 모든 중요한 로직에 대해 테스트를 작성해주세요.
        - 테스트 실행 시간을 고려하세요. 너무 긴 테스트는 CI/CD 파이프라인에 부담을 줄 수 있습니다.
    validations:
      required: true

  - type: textarea
    id: test-notes
    attributes:
      label: 📝 추가 메모
      description: 기타 고려사항이나 주의점이 있다면 작성해주세요.
    validations:
      required: false
