name: Code Quality Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm ci

    - name: Run type check
      run: |
        output=$(npm run type-check 2>&1) || echo "TYPE_CHECK_OUTPUT<<EOF" >> $GITHUB_ENV && echo "$output" >> $GITHUB_ENV && echo "EOF" >> $GITHUB_ENV
      id: type-check

    - name: Run lint
      run: |
        output=$(npm run lint 2>&1) || echo "LINT_OUTPUT<<EOF" >> $GITHUB_ENV && echo "$output" >> $GITHUB_ENV && echo "EOF" >> $GITHUB_ENV
      id: lint

    - name: Create comment
      if: failure()
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const typeCheckOutput = process.env.TYPE_CHECK_OUTPUT;
          const lintOutput = process.env.LINT_OUTPUT;
          
          let comment = '## Code Quality Check Results\n\n';
          
          if (typeCheckOutput) {
            comment += '### Type Check Errors:\n```\n' + typeCheckOutput + '\n```\n\n';
          }
          
          if (lintOutput) {
            comment += '### Lint Errors:\n```\n' + lintOutput + '\n```\n\n';
          }
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.name,
            body: comment
          });