name: Auto Assign Issue Creator
on:
  issues:
    types: [opened]

jobs:
  assignAuthor:
    name: Assign author to Issue
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    steps:
      - name: Assign author to Issue
        uses: technote-space/assign-author@v1
