name: server CI/CD on EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Setup Yarn Berry
      run: |
        cd server
        corepack enable
        yarn set version berry

    - name: Install dependencies
      run: |
          cd server
          yarn install

    - name: Type check
      run: |
        cd server
        yarn type-check
    
    - name: Create .env file
      run: |
          cd server
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env

    - name: Deploy to AWS EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "server/*"
        target: "/var/www/travely"
        strip_components: 1

    - name: Setup environment and start PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/travely
          corepack enable
          yarn set version berry
          yarn build
          yarn start:pm2