name: server CI/CD on EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        cd server
        npm install
    
    - name: Create .env file
      run: |
          cd server
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env

    - name: Deploy to AWS EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "server/*"
        target: "/var/www/your_project_directory"
        strip_components: 1

    - name: Setup environment and start PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/your_project_directory
          npm install
          pm2 start ecosystem.config.js --env production
